### ISSUE TITLE
TODO Region Modal

### ISSUE THREAD

**Issue by abinofbrooklyn** [Jiahao01121/refugee-flow#103]
- [x] Remove use of Emoji Flags
- [x] Capitalize country names
- [x] Set sorting correctly -> Set country order based on total. Keep country locked on box, regardless of count for year.

**Comment by abinofbrooklyn** [comment]
👍
