### ISSUE TITLE
TODO About Page

### ISSUE THREAD

**Issue by abinofbrooklyn** [Jiahao01121/refugee-flow#112]
- [x] Put in Bios

- [ ] Put in links to github and behance

- [ ] Put in data sources
