### ISSUE TITLE
TODO: 7/24 production note

### ISSUE THREAD

**Issue by Jiahao01121** [Jiahao01121/refugee-flow#122]
- [x] order of about page( move first to last, the last one to first), all URL changes to more specific routing.
- [x] Mention route page desc data srouces
- [x] about page=> project team => feedback / contact us
 - [x] change landing page intro button left to transform ( GPU acceleration LINK: https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/)
