### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Jiahao01121** [Jiahao01121/refugee-flow#38]
Asylum Chart TODO:
- [x] Mouseover on currentYear / AllYear
- [x] globe click popups optimization
- [x] tooltips text & Fatality ICON
By Thursday:
- [x] Title and subtitle (the quote)
- [x] change Font of title, nav bar item
- [x] different color code globe data bar.
