### ISSUE TITLE
May 20th - TODO

### ISSUE THREAD

**Issue by Jiahao01121** [Jiahao01121/refugee-flow#71]
- [x] war_all's data structure -- optimize country name by grouping them to object's property.
- [x] modal rank method.
- [x] Server randered WebGL.

- [x] data for asylum application rejection.
