### ISSUE TITLE
TODO Partnerships/Events

### ISSUE THREAD

**Issue by abinofbrooklyn** [Jiahao01121/refugee-flow#99]
- [ ] UNHCR
- [x] IOM
- [ ] American Refugee Committee
- [x] Sea of Solidarity
- [ ] Refugees International
- [ ] Organization for Refuge, Asylum and Migration
- [ ] World Relief
- [ ] IRC
- [ ] Businesses with Refugee/Migration related CSR
- [x] Migration Policy Institue mmittelstadt@migrationpolicy.org
- [ ] Global Citizen?
- [ ] UN Global Compact - Business for Peace
- [ ] UNGA
- [ ] Compact for Migration UN Morocco 
- [ ] Columbia Migration Symposium
